version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000

  timescaledb:
    image: timescale/timescaledb:latest-pg11
    container_name: timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./config/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 5432
    ports:
      - 5432:5432

  adminer:
    image: adminer:standalone
    restart: unless-stopped
    depends_on: 
      - timescaledb
    ports:
      - 8082:8080

  caddy:
    image: abiosoft/caddy:1.0.0-no-stats
    container_name: caddy
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8088:8088"
      - "9090:9090"
      - "9093:9093"
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile

  redis:
    image: redis:5
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis:/data

  postgres:
    image: postgres:11-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  superset:
    image: negbie/superset-docker:git
    container_name: superset
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./config/superset_config.py:/usr/app/superset/superset/superset_config.py
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres:
  redis:

