version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000

  db:
    image: timescale/timescaledb:latest-pg11
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - ./config/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    expose:
      - 5432
    ports:
      - 5432:5432

  adminer:
    image: adminer:standalone
    restart: always
    depends_on: 
      - db
    ports:
      - 8082:8080

  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - postgres:/var/lib/postgresql/data
  superset:
    image: amancevice/superset
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./config/superset_config.py:/etc/superset/superset_config.py
volumes:
  postgres:
  redis: